import { WorkspaceTheme, BookTemplate } from "@/types/theme";

export const WORKSPACE_THEMES: Record<string, WorkspaceTheme> = {
  "warm-ivory": {
    id: "warm-ivory",
    name: "Warm Ivory",
    accentColor: "#D4AF37",
    accentGlow: "rgba(212, 175, 55, 0.15)",
    accentGlowStrong: "rgba(212, 175, 55, 0.4)",
    glassBorder: "border-amber-600/10",
    hoverBg: "hover:bg-amber-600/5",
    selectionColor: "ring-2 ring-[#D4AF37] shadow-[0_0_12px_rgba(212,175,55,0.25)]",
    highlightColor: "#D4AF37",
    isDark: false,
  },
  "soft-linen": {
    id: "soft-linen",
    name: "Soft Linen",
    accentColor: "#2E7D32",
    accentGlow: "rgba(46, 125, 50, 0.12)",
    accentGlowStrong: "rgba(46, 125, 50, 0.35)",
    glassBorder: "border-green-700/10",
    hoverBg: "hover:bg-green-700/5",
    selectionColor: "ring-2 ring-[#2E7D32] shadow-[0_0_12px_rgba(46,125,50,0.2)]",
    highlightColor: "#2E7D32",
    isDark: false,
  },
  "pearl-white": {
    id: "pearl-white",
    name: "Pearl White",
    accentColor: "#B76E79",
    accentGlow: "rgba(183, 110, 121, 0.15)",
    accentGlowStrong: "rgba(183, 110, 121, 0.4)",
    glassBorder: "border-rose-400/10",
    hoverBg: "hover:bg-rose-400/5",
    selectionColor: "ring-2 ring-[#B76E79] shadow-[0_0_12px_rgba(183,110,121,0.25)]",
    highlightColor: "#B76E79",
    isDark: false,
  },
  "alabaster": {
    id: "alabaster",
    name: "Alabaster Ink",
    accentColor: "#2C3E50",
    accentGlow: "rgba(44, 62, 80, 0.1)",
    accentGlowStrong: "rgba(44, 62, 80, 0.3)",
    glassBorder: "border-slate-800/10",
    hoverBg: "hover:bg-slate-800/5",
    selectionColor: "ring-2 ring-[#2C3E50] shadow-[0_0_12px_rgba(44,62,80,0.2)]",
    highlightColor: "#2C3E50",
    isDark: false,
  },
  "midnight-gold": {
    id: "midnight-gold",
    name: "Midnight Gold",
    accentColor: "#D4AF37",
    accentGlow: "rgba(212, 175, 55, 0.2)",
    accentGlowStrong: "rgba(212, 175, 55, 0.45)",
    glassBorder: "border-amber-500/20",
    hoverBg: "hover:bg-amber-500/10",
    selectionColor: "ring-2 ring-[#D4AF37] shadow-[0_0_12px_rgba(212,175,55,0.4)]",
    highlightColor: "#D4AF37",
    isDark: true,
  },
  "ocean-blue": {
    id: "ocean-blue",
    name: "Ocean Blue",
    accentColor: "#00E5FF",
    accentGlow: "rgba(0, 229, 255, 0.25)",
    accentGlowStrong: "rgba(0, 229, 255, 0.5)",
    glassBorder: "border-cyan-500/20",
    hoverBg: "hover:bg-cyan-500/10",
    selectionColor: "ring-2 ring-[#00E5FF] shadow-[0_0_12px_rgba(0,229,255,0.4)]",
    highlightColor: "#00E5FF",
    isDark: true,
  },
  "emerald": {
    id: "emerald",
    name: "Emerald Green",
    accentColor: "#00E676",
    accentGlow: "rgba(0, 230, 118, 0.2)",
    accentGlowStrong: "rgba(0, 230, 118, 0.45)",
    glassBorder: "border-emerald-500/20",
    hoverBg: "hover:bg-emerald-500/10",
    selectionColor: "ring-2 ring-[#00E676] shadow-[0_0_12px_rgba(0,230,118,0.4)]",
    highlightColor: "#00E676",
    isDark: true,
  },
  "crimson": {
    id: "crimson",
    name: "Crimson Red",
    accentColor: "#FF1744",
    accentGlow: "rgba(255, 23, 68, 0.2)",
    accentGlowStrong: "rgba(255, 23, 68, 0.5)",
    glassBorder: "border-red-500/20",
    hoverBg: "hover:bg-red-500/10",
    selectionColor: "ring-2 ring-[#FF1744] shadow-[0_0_12px_rgba(255,23,68,0.4)]",
    highlightColor: "#FF1744",
    isDark: true,
  },
  "violet": {
    id: "violet",
    name: "Royal Violet",
    accentColor: "#D500F9",
    accentGlow: "rgba(213, 0, 249, 0.25)",
    accentGlowStrong: "rgba(213, 0, 249, 0.5)",
    glassBorder: "border-purple-500/20",
    hoverBg: "hover:bg-purple-500/10",
    selectionColor: "ring-2 ring-[#D500F9] shadow-[0_0_12px_rgba(213,0,249,0.4)]",
    highlightColor: "#D500F9",
    isDark: true,
  },
  "graphite": {
    id: "graphite",
    name: "Graphite Silver",
    accentColor: "#E0E0E0",
    accentGlow: "rgba(224, 224, 224, 0.15)",
    accentGlowStrong: "rgba(224, 224, 224, 0.35)",
    glassBorder: "border-neutral-400/20",
    hoverBg: "hover:bg-neutral-400/10",
    selectionColor: "ring-2 ring-white shadow-[0_0_12px_rgba(255,255,255,0.2)]",
    highlightColor: "#E0E0E0",
    isDark: true,
  },
  "slate": {
    id: "slate",
    name: "Slate Blue",
    accentColor: "#90A4AE",
    accentGlow: "rgba(144, 164, 174, 0.2)",
    accentGlowStrong: "rgba(144, 164, 174, 0.4)",
    glassBorder: "border-slate-400/20",
    hoverBg: "hover:bg-slate-400/10",
    selectionColor: "ring-2 ring-[#90A4AE] shadow-[0_0_12px_rgba(144,164,174,0.3)]",
    highlightColor: "#90A4AE",
    isDark: true,
  },
};

export const BOOK_TEMPLATES: Record<string, BookTemplate> = {
  fantasy: {
    id: "fantasy",
    name: "Fantasy Legend",
    category: "Fantasy",
    description: "Gilded drop caps, double borders, and classical serif headers for mythic tales.",
    fonts: {
      title: "Cinzel",
      body: "Playfair Display",
      subtitle: "Playfair Display",
    },
    colors: {
      paperTint: "#F7F2E9",
      textDark: "#1A1A1A",
      textMuted: "#4F4B41",
      accent: "#D4AF37",
    },
    borders: {
      borderStyle: "border-2 border-[#D4AF37]/30 ring-1 ring-[#D4AF37]/10 ring-offset-4 ring-offset-[#F7F2E9]",
      decorativeCorners: true,
    },
    decorations: {
      ornaments: true,
      dividerStyle: "border-double border-b-4 border-[#D4AF37]/50 w-24 mx-auto my-3",
    },
    paperTexture: "radial-gradient(circle, #FAF7F2 0%, #EFE9DE 100%)",
    margins: "normal",
    chapterStyle: {
      numberFont: "Cinzel",
      titleFont: "Cinzel",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "bg-[#D4AF37]/10 border border-[#D4AF37]/50 text-[#D4AF37] font-cinzel rounded px-1.5 mr-2 float-left text-4xl font-bold leading-[0.9]",
    },
    typography: {
      lineHeight: 1.6,
      letterSpacing: 0,
    },
  },
  scifi: {
    id: "scifi",
    name: "Sci-Fi Core",
    category: "Sci-Fi",
    description: "Monospace tags, thin borders, and structured layouts matching galactic logs.",
    fonts: {
      title: "Orbitron",
      body: "Inter",
      subtitle: "Orbitron",
    },
    colors: {
      paperTint: "#EBF5F8",
      textDark: "#111D25",
      textMuted: "#465866",
      accent: "#00E5FF",
    },
    borders: {
      borderStyle: "border border-[#00E5FF]/20 relative before:absolute before:top-2 before:left-2 before:w-2 before:h-2 before:border-t before:border-l before:border-[#00E5FF] after:absolute after:bottom-2 after:right-2 after:w-2 after:h-2 after:border-b after:border-r after:border-[#00E5FF]",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: false,
      dividerStyle: "border-t border-dashed border-[#00E5FF]/30 w-36 mx-auto my-4",
    },
    paperTexture: "linear-gradient(135deg, #F0F7F9 0%, #DCEEF3 100%)",
    margins: "wide",
    chapterStyle: {
      numberFont: "Orbitron",
      titleFont: "Orbitron",
      alignment: "left",
    },
    dropCap: {
      enabled: false,
      style: "",
    },
    typography: {
      lineHeight: 1.5,
      letterSpacing: 0.8,
    },
  },
  horror: {
    id: "horror",
    name: "Gothic Horror",
    category: "Horror",
    description: "Grim distressed parchment tones and jagged, tall-cap title settings.",
    fonts: {
      title: "Creepster",
      body: "Playfair Display",
      subtitle: "Playfair Display",
    },
    colors: {
      paperTint: "#E2DCD4",
      textDark: "#1A0F0F",
      textMuted: "#4E3C3C",
      accent: "#FF1744",
    },
    borders: {
      borderStyle: "border border-[#FF1744]/20 outline outline-1 outline-[#FF1744]/5 outline-offset-4",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: false,
      dividerStyle: "h-[1px] bg-gradient-to-r from-transparent via-[#FF1744]/40 to-transparent w-40 mx-auto my-4",
    },
    paperTexture: "radial-gradient(circle, #EADFDF 0%, #CEBEBE 100%)",
    margins: "normal",
    chapterStyle: {
      numberFont: "Creepster",
      titleFont: "Creepster",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "bg-black text-[#FF1744] font-creepster border border-[#FF1744]/30 rounded px-2 mr-2 float-left text-4xl leading-[1.0] shadow-sm",
    },
    typography: {
      lineHeight: 1.6,
      letterSpacing: 0,
    },
  },
  romance: {
    id: "romance",
    name: "Classic Romance",
    category: "Romance",
    description: "Elegant script calligraphy headers and soft rose-tinted poetry margins.",
    fonts: {
      title: "Alex Brush",
      body: "Cormorant Garamond",
      subtitle: "Cormorant Garamond",
    },
    colors: {
      paperTint: "#FAF2F2",
      textDark: "#2C1A1E",
      textMuted: "#7D5961",
      accent: "#B76E79",
    },
    borders: {
      borderStyle: "border border-dashed border-[#B76E79]/20 rounded-md p-1",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: true,
      dividerStyle: "border-b border-[#B76E79]/30 w-24 mx-auto my-3 relative after:content-['♥'] after:absolute after:-top-2.5 after:left-1/2 after:-translate-x-1/2 after:bg-[#FAF2F2] after:px-1 after:text-[10px] after:text-[#B76E79]",
    },
    paperTexture: "radial-gradient(circle, #FDFBFB 0%, #F5EAEB 100%)",
    margins: "narrow",
    chapterStyle: {
      numberFont: "Alex Brush",
      titleFont: "Alex Brush",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "text-[#B76E79] font-alex italic text-5xl mr-1.5 float-left leading-[0.8]",
    },
    typography: {
      lineHeight: 1.7,
      letterSpacing: 0.4,
    },
  },
  adventure: {
    id: "adventure",
    name: "Uncharted Adventure",
    category: "Adventure",
    description: "Distressed typewriter titles, rustic leather styling, and spacious sepia framing.",
    fonts: {
      title: "Special Elite",
      body: "Cormorant Garamond",
      subtitle: "Special Elite",
    },
    colors: {
      paperTint: "#F4EFE3",
      textDark: "#242018",
      textMuted: "#6B604A",
      accent: "#00E676",
    },
    borders: {
      borderStyle: "border border-[#8B7355]/20 p-0.5 outline outline-1 outline-neutral-800/10",
      decorativeCorners: true,
    },
    decorations: {
      ornaments: false,
      dividerStyle: "border-b border-dotted border-neutral-500/40 w-36 mx-auto my-4",
    },
    paperTexture: "linear-gradient(to bottom, #FAF5EA, #E3D9C4)",
    margins: "normal",
    chapterStyle: {
      numberFont: "Special Elite",
      titleFont: "Special Elite",
      alignment: "left",
    },
    dropCap: {
      enabled: true,
      style: "bg-neutral-800 text-white font-special border border-neutral-700 rounded px-2 mr-2 float-left text-3xl leading-[1.1] shadow-md",
    },
    typography: {
      lineHeight: 1.6,
      letterSpacing: 0,
    },
  },
  children: {
    id: "children",
    name: "Fairytale Childhood",
    category: "Children",
    description: "Rounded, friendly fonts and double board edges with colorful text guidelines.",
    fonts: {
      title: "Fredoka",
      body: "Fredoka",
      subtitle: "Fredoka",
    },
    colors: {
      paperTint: "#FFFDEB",
      textDark: "#2B2412",
      textMuted: "#726544",
      accent: "#D500F9",
    },
    borders: {
      borderStyle: "border-4 border-double border-[#D500F9]/20 rounded-xl p-1",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: true,
      dividerStyle: "h-1 bg-gradient-to-r from-transparent via-[#D500F9]/30 to-transparent rounded-full w-28 mx-auto my-3",
    },
    paperTexture: "radial-gradient(circle, #FFFDF0 0%, #FFF9C4 100%)",
    margins: "wide",
    chapterStyle: {
      numberFont: "Fredoka",
      titleFont: "Fredoka",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "bg-gradient-to-br from-[#D500F9]/10 to-[#00E5FF]/10 border border-[#D500F9]/30 text-[#D500F9] font-fredoka rounded-full w-10 h-10 flex items-center justify-center mr-2 float-left text-2xl font-bold leading-none shadow-inner",
    },
    typography: {
      lineHeight: 1.5,
      letterSpacing: 0.5,
    },
  },
  classic: {
    id: "classic",
    name: "Classic Academic",
    category: "Classic",
    description: "Stately serif letterings, delicate hair-rules, and generous margins.",
    fonts: {
      title: "Cormorant Garamond",
      body: "Cormorant Garamond",
      subtitle: "Cormorant Garamond",
    },
    colors: {
      paperTint: "#FCFAF6",
      textDark: "#1F1F1F",
      textMuted: "#606060",
      accent: "#E0E0E0",
    },
    borders: {
      borderStyle: "border border-neutral-200/50 shadow-xs",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: true,
      dividerStyle: "border-b border-neutral-300 w-16 mx-auto my-4",
    },
    paperTexture: "radial-gradient(circle, #FFFFFF 0%, #F5F1E9 100%)",
    margins: "normal",
    chapterStyle: {
      numberFont: "Cormorant Garamond",
      titleFont: "Cormorant Garamond",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "text-neutral-900 font-cormorant font-bold text-5xl mr-2 float-left leading-[0.8] pt-1",
    },
    typography: {
      lineHeight: 1.7,
      letterSpacing: 0.2,
    },
  },
  minimal: {
    id: "minimal",
    name: "Minimalist Modern",
    category: "Minimal",
    description: "Clean sans-serif fonts, thin structural layouts, and pure white spaces.",
    fonts: {
      title: "Inter",
      body: "Inter",
      subtitle: "Inter",
    },
    colors: {
      paperTint: "#FFFFFF",
      textDark: "#1C1C1C",
      textMuted: "#6E6E6E",
      accent: "#333333",
    },
    borders: {
      borderStyle: "border border-neutral-100",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: false,
      dividerStyle: "border-t border-neutral-200 w-12 mx-auto my-4",
    },
    paperTexture: "none",
    margins: "normal",
    chapterStyle: {
      numberFont: "Inter",
      titleFont: "Inter",
      alignment: "left",
    },
    dropCap: {
      enabled: false,
      style: "",
    },
    typography: {
      lineHeight: 1.6,
      letterSpacing: -0.2,
    },
  },
  fairytale: {
    id: "fairytale",
    name: "Magical Fairy Tale",
    category: "Children",
    description: "Enchanted borders, star dividers, and medieval display styling.",
    fonts: {
      title: "Cinzel",
      body: "Cormorant Garamond",
      subtitle: "Cinzel",
    },
    colors: {
      paperTint: "#FAF5EC",
      textDark: "#1F190D",
      textMuted: "#63563F",
      accent: "#D4AF37",
    },
    borders: {
      borderStyle: "border-4 border-double border-[#D4AF37]/40 rounded-lg p-2",
      decorativeCorners: true,
    },
    decorations: {
      ornaments: true,
      dividerStyle: "border-b border-[#D4AF37]/35 w-24 mx-auto my-4 relative after:content-['✦'] after:absolute after:-top-3 after:left-1/2 after:-translate-x-1/2 after:bg-[#FAF5EC] after:px-1 after:text-xs after:text-[#D4AF37]",
    },
    paperTexture: "radial-gradient(circle, #FFFDF8 0%, #F5ECD7 100%)",
    margins: "normal",
    chapterStyle: {
      numberFont: "Cinzel",
      titleFont: "Cinzel",
      alignment: "center",
    },
    dropCap: {
      enabled: true,
      style: "bg-[#D4AF37]/15 text-[#D4AF37] font-cinzel rounded border border-[#D4AF37]/50 w-9 h-9 flex items-center justify-center mr-2 float-left text-xl font-bold leading-none shadow-sm",
    },
    typography: {
      lineHeight: 1.6,
      letterSpacing: 0.3,
    },
  },
  poetry: {
    id: "poetry",
    name: "Delicate Poetry",
    category: "Poetry",
    description: "Elegant, side-ruled margins, wide spacings, and romantic italic subtitles.",
    fonts: {
      title: "Playfair Display",
      body: "Cormorant Garamond",
      subtitle: "Playfair Display",
    },
    colors: {
      paperTint: "#FDFDFD",
      textDark: "#222222",
      textMuted: "#6E6E6E",
      accent: "#9E9E9E",
    },
    borders: {
      borderStyle: "border-l border-neutral-300 pl-4",
      decorativeCorners: false,
    },
    decorations: {
      ornaments: false,
      dividerStyle: "border-t border-neutral-100 w-8 mx-auto my-4",
    },
    paperTexture: "none",
    margins: "normal",
    chapterStyle: {
      numberFont: "Playfair Display",
      titleFont: "Playfair Display",
      alignment: "left",
    },
    dropCap: {
      enabled: false,
      style: "",
    },
    typography: {
      lineHeight: 1.8,
      letterSpacing: 0.6,
    },
  },
};

export const THEMES = BOOK_TEMPLATES;
